fix incorrect if statement

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -50,6 +50,8 @@ jobs:
           ZIP_NAME=$(find . -type f -name 'rana_qgis_plugin.*.zip')
           if wget --spider https://plugins.lizard.net/${ZIP_NAME} 2>/dev/null;
           then
+            echo "Cannot upload $ZIP_NAME; file is already present on plugins.lizard.net> &2 && exit 1"
+          else
             curl -X POST \
                 --retry 3 \
                 --progress-bar \
@@ -57,8 +59,6 @@ jobs:
                 -F key=${ARTIFACTS_SERVER_KEY} \
                 -F artifact=@${ZIP_NAME} \
                 https://artifacts.lizard.net/upload/rana-qgis-plugin/
-          else
-            echo "Cannot upload $ZIP_NAME; file is already present on plugins.lizard.net> &2 && exit 1"
           fi
         env:
           ARTIFACTS_SERVER_KEY: ${{ secrets.ARTIFACTS_KEY }}
